// Địa điểm hành chính Việt Nam (Province, District, Ward)
export interface Ward {
    value: string;
    label: string;
}

export interface District {
    value: string;
    label: string;
    wards: Ward[];
}

export interface Province {
    value: string;
    label: string;
    districts: District[];
}

// Dữ liệu tỉnh/thành phố - Quận/Huyện - Phường/Xã (mẫu cho TP.HCM và một số tỉnh)
export const provinces: Province[] = [
    {
        value: 'hochiminh',
        label: 'TP. Hồ Chí Minh',
        districts: [
            {
                value: 'quan1',
                label: 'Quận 1',
                wards: [
                    { value: 'bennghe', label: 'Phường Bến Nghé' },
                    { value: 'benthanh', label: 'Phường Bến Thành' },
                    { value: 'caovanlinh', label: 'Phường Cô Giang' },
                    { value: 'caubongchoi', label: 'Phường Cầu Kho' },
                    { value: 'dakaonuoc', label: 'Phường Đa Kao' },
                    { value: 'nguyen-thai-binh', label: 'Phường Nguyễn Thái Bình' },
                    { value: 'pham-ngu-lao', label: 'Phường Phạm Ngũ Lão' },
                    { value: 'nguyen-cu-trinh', label: 'Phường Nguyễn Cư Trinh' },
                    { value: 'tan-dinh', label: 'Phường Tân Định' },
                ],
            },
            {
                value: 'quan3',
                label: 'Quận 3',
                wards: [
                    { value: 'ward1', label: 'Phường 1' },
                    { value: 'ward2', label: 'Phường 2' },
                    { value: 'ward3', label: 'Phường 3' },
                    { value: 'ward4', label: 'Phường 4' },
                    { value: 'ward5', label: 'Phường 5' },
                    { value: 'ward6', label: 'Phường 6' },
                    { value: 'ward9', label: 'Phường 9' },
                    { value: 'ward10', label: 'Phường 10' },
                    { value: 'ward11', label: 'Phường 11' },
                    { value: 'ward12', label: 'Phường 12' },
                    { value: 'ward13', label: 'Phường 13' },
                    { value: 'ward14', label: 'Phường 14' },
                ],
            },
            {
                value: 'quan5',
                label: 'Quận 5',
                wards: [
                    { value: 'ward1', label: 'Phường 1' },
                    { value: 'ward2', label: 'Phường 2' },
                    { value: 'ward3', label: 'Phường 3' },
                    { value: 'ward4', label: 'Phường 4' },
                    { value: 'ward5', label: 'Phường 5' },
                    { value: 'ward6', label: 'Phường 6' },
                    { value: 'ward7', label: 'Phường 7' },
                    { value: 'ward8', label: 'Phường 8' },
                    { value: 'ward9', label: 'Phường 9' },
                    { value: 'ward10', label: 'Phường 10' },
                    { value: 'ward11', label: 'Phường 11' },
                    { value: 'ward12', label: 'Phường 12' },
                    { value: 'ward13', label: 'Phường 13' },
                    { value: 'ward14', label: 'Phường 14' },
                    { value: 'ward15', label: 'Phường 15' },
                ],
            },
            {
                value: 'quantanbinh',
                label: 'Quận Tân Bình',
                wards: [
                    { value: 'ward1', label: 'Phường 1' },
                    { value: 'ward2', label: 'Phường 2' },
                    { value: 'ward3', label: 'Phường 3' },
                    { value: 'ward4', label: 'Phường 4' },
                    { value: 'ward5', label: 'Phường 5' },
                    { value: 'ward6', label: 'Phường 6' },
                    { value: 'ward7', label: 'Phường 7' },
                    { value: 'ward8', label: 'Phường 8' },
                    { value: 'ward10', label: 'Phường 10' },
                    { value: 'ward11', label: 'Phường 11' },
                    { value: 'ward12', label: 'Phường 12' },
                    { value: 'ward13', label: 'Phường 13' },
                    { value: 'ward14', label: 'Phường 14' },
                    { value: 'ward15', label: 'Phường 15' },
                ],
            },
            {
                value: 'quantanphu',
                label: 'Quận Tân Phú',
                wards: [
                    { value: 'hieuphuoc', label: 'Phường Hiệp Phú' },
                    { value: 'hoa-thanh', label: 'Phường Hòa Thạnh' },
                    { value: 'phu-thanh', label: 'Phường Phú Thạnh' },
                    { value: 'phu-tho-hoa', label: 'Phường Phú Thọ Hòa' },
                    { value: 'phu-trung', label: 'Phường Phú Trung' },
                    { value: 'son-ky', label: 'Phường Sơn Kỳ' },
                    { value: 'tan-quy', label: 'Phường Tân Quý' },
                    { value: 'tan-son-nhi', label: 'Phường Tân Sơn Nhì' },
                    { value: 'tan-thanh', label: 'Phường Tân Thành' },
                    { value: 'tan-thoi-hoa', label: 'Phường Tân Thới Hòa' },
                    { value: 'tay-thanh', label: 'Phường Tây Thạnh' },
                ],
            },
            {
                value: 'binhtan',
                label: 'Quận Bình Tân',
                wards: [
                    { value: 'an-lac', label: 'Phường An Lạc' },
                    { value: 'an-lac-a', label: 'Phường An Lạc A' },
                    { value: 'binh-hung-hoa', label: 'Phường Bình Hưng Hòa' },
                    { value: 'binh-hung-hoa-a', label: 'Phường Bình Hưng Hòa A' },
                    { value: 'binh-hung-hoa-b', label: 'Phường Bình Hưng Hòa B' },
                    { value: 'binh-tri-dong', label: 'Phường Bình Trị Đông' },
                    { value: 'binh-tri-dong-a', label: 'Phường Bình Trị Đông A' },
                    { value: 'binh-tri-dong-b', label: 'Phường Bình Trị Đông B' },
                    { value: 'tan-tao', label: 'Phường Tân Tạo' },
                    { value: 'tan-tao-a', label: 'Phường Tân Tạo A' },
                ],
            },
            {
                value: 'thu-duc',
                label: 'Thành phố Thủ Đức',
                wards: [
                    { value: 'an-khanh', label: 'Phường An Khánh' },
                    { value: 'an-loi-dong', label: 'Phường An Lợi Đông' },
                    { value: 'an-phu', label: 'Phường An Phú' },
                    { value: 'binh-an', label: 'Phường Bình An' },
                    { value: 'binh-chieu', label: 'Phường Bình Chiểu' },
                    { value: 'binh-tho', label: 'Phường Bình Thọ' },
                    { value: 'binh-trung-dong', label: 'Phường Bình Trưng Đông' },
                    { value: 'binh-trung-tay', label: 'Phường Bình Trưng Tây' },
                    { value: 'cat-lai', label: 'Phường Cát Lái' },
                    { value: 'hiep-binh-chanh', label: 'Phường Hiệp Bình Chánh' },
                    { value: 'hiep-binh-phuoc', label: 'Phường Hiệp Bình Phước' },
                    { value: 'linh-chieu', label: 'Phường Linh Chiểu' },
                    { value: 'linh-dong', label: 'Phường Linh Đông' },
                    { value: 'linh-tay', label: 'Phường Linh Tây' },
                    { value: 'linh-trung', label: 'Phường Linh Trung' },
                    { value: 'linh-xuan', label: 'Phường Linh Xuân' },
                    { value: 'phuoc-binh', label: 'Phường Phước Bình' },
                    { value: 'phuoc-long-a', label: 'Phường Phước Long A' },
                    { value: 'phuoc-long-b', label: 'Phường Phước Long B' },
                    { value: 'tam-binh', label: 'Phường Tam Bình' },
                    { value: 'tam-phu', label: 'Phường Tam Phú' },
                    { value: 'tan-phu', label: 'Phường Tân Phú' },
                    { value: 'thao-dien', label: 'Phường Thảo Điền' },
                    { value: 'thanh-my-loi', label: 'Phường Thạnh Mỹ Lợi' },
                    { value: 'truong-tho', label: 'Phường Trường Thọ' },
                ],
            },
        ],
    },
    {
        value: 'binhduong',
        label: 'Bình Dương',
        districts: [
            {
                value: 'thu-dau-mot',
                label: 'Thành phố Thủ Dầu Một',
                wards: [
                    { value: 'chanh-nghia', label: 'Phường Chánh Nghĩa' },
                    { value: 'chanh-my', label: 'Phường Chánh Mỹ' },
                    { value: 'hiep-an', label: 'Phường Hiệp An' },
                    { value: 'hiep-thanh', label: 'Phường Hiệp Thành' },
                    { value: 'hoa-phu', label: 'Phường Hòa Phú' },
                    { value: 'phu-cuong', label: 'Phường Phú Cường' },
                    { value: 'phu-hoa', label: 'Phường Phú Hòa' },
                    { value: 'phu-loi', label: 'Phường Phú Lợi' },
                    { value: 'phu-my', label: 'Phường Phú Mỹ' },
                    { value: 'phu-tan', label: 'Phường Phú Tân' },
                    { value: 'phu-tho', label: 'Phường Phú Thọ' },
                    { value: 'tan-an', label: 'Phường Tân An' },
                    { value: 'tuong-binh-hiep', label: 'Phường Tương Bình Hiệp' },
                ],
            },
            {
                value: 'di-an',
                label: 'Thành phố Dĩ An',
                wards: [
                    { value: 'an-binh', label: 'Phường An Bình' },
                    { value: 'binh-an', label: 'Phường Bình An' },
                    { value: 'binh-thang', label: 'Phường Bình Thắng' },
                    { value: 'di-an', label: 'Phường Dĩ An' },
                    { value: 'dong-hoa', label: 'Phường Đông Hòa' },
                    { value: 'tan-binh', label: 'Phường Tân Bình' },
                    { value: 'tan-dong-hiep', label: 'Phường Tân Đông Hiệp' },
                ],
            },
            {
                value: 'thuan-an',
                label: 'Thành phố Thuận An',
                wards: [
                    { value: 'an-phu', label: 'Phường An Phú' },
                    { value: 'an-son', label: 'Phường An Sơn' },
                    { value: 'an-thanh', label: 'Phường An Thạnh' },
                    { value: 'binh-chuan', label: 'Phường Bình Chuẩn' },
                    { value: 'binh-hoa', label: 'Phường Bình Hòa' },
                    { value: 'binh-nham', label: 'Phường Bình Nhâm' },
                    { value: 'hung-dinh', label: 'Phường Hưng Định' },
                    { value: 'lai-thieu', label: 'Phường Lái Thiêu' },
                    { value: 'thuan-giao', label: 'Phường Thuận Giao' },
                    { value: 'vinh-phu', label: 'Phường Vĩnh Phú' },
                ],
            },
        ],
    },
    {
        value: 'dongnai',
        label: 'Đồng Nai',
        districts: [
            {
                value: 'bien-hoa',
                label: 'Thành phố Biên Hòa',
                wards: [
                    { value: 'an-binh', label: 'Phường An Bình' },
                    { value: 'an-hoa', label: 'Phường An Hòa' },
                    { value: 'binh-da', label: 'Phường Bình Đa' },
                    { value: 'hoa-binh', label: 'Phường Hòa Bình' },
                    { value: 'ho-nai', label: 'Phường Hố Nai' },
                    { value: 'long-binh', label: 'Phường Long Bình' },
                    { value: 'long-binh-tan', label: 'Phường Long Bình Tân' },
                    { value: 'phuoc-tan', label: 'Phường Phước Tân' },
                    { value: 'quyet-thang', label: 'Phường Quyết Thắng' },
                    { value: 'tam-hiep', label: 'Phường Tam Hiệp' },
                    { value: 'tam-hoa', label: 'Phường Tam Hòa' },
                    { value: 'tan-binh', label: 'Phường Tân Biên' },
                    { value: 'tan-hiep', label: 'Phường Tân Hiệp' },
                    { value: 'tan-hoa', label: 'Phường Tân Hòa' },
                    { value: 'tan-mai', label: 'Phường Tân Mai' },
                    { value: 'tan-phong', label: 'Phường Tân Phong' },
                    { value: 'tan-tien', label: 'Phường Tân Tiến' },
                    { value: 'tan-van', label: 'Phường Tân Vạn' },
                    { value: 'thanh-binh', label: 'Phường Thành Bình' },
                    { value: 'trang-dai', label: 'Phường Trảng Dài' },
                ],
            },
            {
                value: 'long-khanh',
                label: 'Thành phố Long Khánh',
                wards: [
                    { value: 'bao-quang', label: 'Phường Bảo Quang' },
                    { value: 'bao-vinh', label: 'Phường Bảo Vinh' },
                    { value: 'phu-binh', label: 'Phường Phú Bình' },
                    { value: 'suoi-tre', label: 'Phường Suối Tre' },
                    { value: 'xuan-an', label: 'Phường Xuân An' },
                    { value: 'xuan-binh', label: 'Phường Xuân Bình' },
                    { value: 'xuan-hoa', label: 'Phường Xuân Hòa' },
                    { value: 'xuan-lap', label: 'Phường Xuân Lập' },
                    { value: 'xuan-thanh', label: 'Phường Xuân Thanh' },
                    { value: 'xuan-trung', label: 'Phường Xuân Trung' },
                ],
            },
        ],
    },
    {
        value: 'vungtau',
        label: 'Bà Rịa - Vũng Tàu',
        districts: [
            {
                value: 'vung-tau',
                label: 'Thành phố Vũng Tàu',
                wards: [
                    { value: 'ward1', label: 'Phường 1' },
                    { value: 'ward2', label: 'Phường 2' },
                    { value: 'ward3', label: 'Phường 3' },
                    { value: 'ward4', label: 'Phường 4' },
                    { value: 'ward5', label: 'Phường 5' },
                    { value: 'ward7', label: 'Phường 7' },
                    { value: 'ward8', label: 'Phường 8' },
                    { value: 'ward9', label: 'Phường 9' },
                    { value: 'ward10', label: 'Phường 10' },
                    { value: 'ward11', label: 'Phường 11' },
                    { value: 'ward12', label: 'Phường 12' },
                    { value: 'nguyen-an-ninh', label: 'Phường Nguyễn An Ninh' },
                    { value: 'rach-dua', label: 'Phường Rạch Dừa' },
                    { value: 'thang-nhat', label: 'Phường Thắng Nhất' },
                    { value: 'thang-nhi', label: 'Phường Thắng Nhì' },
                    { value: 'thang-tam', label: 'Phường Thắng Tam' },
                ],
            },
            {
                value: 'ba-ria',
                label: 'Thành phố Bà Rịa',
                wards: [
                    { value: 'kim-dinh', label: 'Phường Kim Dinh' },
                    { value: 'long-huong', label: 'Phường Long Hương' },
                    { value: 'long-tam', label: 'Phường Long Tâm' },
                    { value: 'long-toan', label: 'Phường Long Toàn' },
                    { value: 'phu-my', label: 'Phường Phú Mỹ' },
                    { value: 'phu-trieu', label: 'Phường Phú Triều' },
                    { value: 'tan-hiep', label: 'Phường Tân Hiệp' },
                    { value: 'tan-hoa', label: 'Phường Tân Hòa' },
                ],
            },
        ],
    },
    {
        value: 'hanoi',
        label: 'Hà Nội',
        districts: [
            {
                value: 'hoan-kiem',
                label: 'Quận Hoàn Kiếm',
                wards: [
                    { value: 'cua-dong', label: 'Phường Cửa Đông' },
                    { value: 'cua-nam', label: 'Phường Cửa Nam' },
                    { value: 'dong-xuan', label: 'Phường Đồng Xuân' },
                    { value: 'hang-bac', label: 'Phường Hàng Bạc' },
                    { value: 'hang-bo', label: 'Phường Hàng Bồ' },
                    { value: 'hang-buom', label: 'Phường Hàng Buồm' },
                    { value: 'hang-dao', label: 'Phường Hàng Đào' },
                    { value: 'hang-gai', label: 'Phường Hàng Gai' },
                    { value: 'hang-ma', label: 'Phường Hàng Mã' },
                    { value: 'hang-trong', label: 'Phường Hàng Trống' },
                    { value: 'ly-thai-to', label: 'Phường Lý Thái Tổ' },
                    { value: 'phan-chu-trinh', label: 'Phường Phan Chu Trinh' },
                    { value: 'tran-hung-dao', label: 'Phường Trần Hưng Đạo' },
                ],
            },
            {
                value: 'ba-dinh',
                label: 'Quận Ba Đình',
                wards: [
                    { value: 'cong-vi', label: 'Phường Cống Vị' },
                    { value: 'dien-bien', label: 'Phường Điện Biên' },
                    { value: 'doi-can', label: 'Phường Đội Cấn' },
                    { value: 'giang-vo', label: 'Phường Giảng Võ' },
                    { value: 'kim-ma', label: 'Phường Kim Mã' },
                    { value: 'lieu-giai', label: 'Phường Liễu Giai' },
                    { value: 'ngoc-ha', label: 'Phường Ngọc Hà' },
                    { value: 'ngoc-khanh', label: 'Phường Ngọc Khánh' },
                    { value: 'nguyen-trung-truc', label: 'Phường Nguyễn Trung Trực' },
                    { value: 'quan-thanh', label: 'Phường Quán Thánh' },
                    { value: 'thanh-cong', label: 'Phường Thành Công' },
                    { value: 'truc-bach', label: 'Phường Trúc Bạch' },
                    { value: 'vinh-phuc', label: 'Phường Vĩnh Phúc' },
                ],
            },
        ],
    },
];
