spring.application.name=capstone


server.servlet.context-path=/api/v1

#DB
spring.datasource.username=trinhan
spring.datasource.password=Anneh123321@
spring.datasource.url=jdbc:mysql://capstone.mysql.database.azure.com:3306/capstone_tamtech?useSSL=true&serverTimezone=Asia/Ho_Chi_Minh

#-----------------------THIS IS LOCAL--------------------------#

#spring.datasource.username=root
#spring.datasource.password=12345
#spring.datasource.url=jdbc:mysql://localhost:3306/capstone_tamtech?useSSL=true&serverTimezone=UTC


spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
jwt.secretkey=D7YyilSUf+tKB/WUsifAHksqf32h8p9Ua2vFuLCWzJ8=



#Time
spring.jackson.time-zone=Asia/Ho_Chi_Minh

# set up zalo otp
zalo.url=https://api.abenla.com/api/SendSms
zalo.loginName=ABMU127
zalo.sign=673090a5ae6a931005b4dfb24a2a2de3
zalo.serviceTypeId=537
zalo.brandName=ZOTP

#Google map api
google.map.api=https://maps.googleapis.com/maps/api

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.packages-to-scan=com.capstone.tamtech.capstone.controllers
springdoc.show-actuator=false

#Gmail Config
spring.mail.default-encoding=UTF-8
spring.mail.test-connection=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ngocanpro1234321@gmail.com
spring.mail.password=dhya kkri ages qhpg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#Redis Config
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000

#Google map
google.map.key=AIzaSyDG_BzswCLO3QGtZWQ0sZet9mfv3ZmUB2I

#PAYOS
PAYOS_CLIENT_ID=a877dbe3-6f42-4513-a220-2235daabc520
PAYOS_API_KEY=27172560-3484-4e43-981a-e5484cc32c20
PAYOS_CHECKSUM_KEY=eaa35201de4f819b57d8d8b9c518d79a4d3f5b1f7f532280a5288e7f5f650395

supabase.url=https://jrywfuumgozrxpfkokos.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyeXdmdXVtZ296cnhwZmtva29zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMTYxMjksImV4cCI6MjA3ODU5MjEyOX0.rXh29XzHNW9en_fWdQcXsE6rd7hXYZ5K6TnL43xtGvs
supabase.bucket.name=tamtech-billing


